### ISSUE TITLE
URI.encode can't handle lists

### ISSUE THREAD

**Issue by drapergeek** [elixirdrops/kerosene#10]
Hello!

I was checking out your project for pagination and found what may be an issue for others. If you have a form that puts elements into a list for a single attribute. `URI.encode` can't handle that in the `build_query` function: https://github.com/elixirdrops/kerosene/blob/master/lib/kerosene/paginator.ex#L88. This throws an exception if you have something like `%{"user_ids" => [1,2]}`.

I quickly checked and it seems that `Plug.Conn.Query.encode/2` can handle this and may be an appropriate replacement: https://hexdocs.pm/plug/Plug.Conn.Query.html#encode/2

**Comment by JustinAiken** [comment]
Heh, I just ran into this same issue! 

```elixir
protocol String.Chars not implemented for %{"some_param" => "foo"}

** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol String.Chars not implemented for %{"some_param" => "foo"}
        (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
        (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
        (elixir) lib/uri.ex:105: URI.encode_kv_pair/1
        (elixir) lib/enum.ex:1216: anonymous fn/4 in Enum.map_join/3
        (stdlib) lists.erl:1263: :lists.foldl/3
        (elixir) lib/enum.ex:1214: Enum.map_join/3
        lib/kerosene/paginator.ex:82: Kerosene.Paginator.build_url/2
        lib/kerosene/paginator.ex:23: anonymous fn/5 in Kerosene.Paginator.paginate/3
```

**Comment by allyraza** [comment]
Hi,

Makes sense I will take a look at it as soon as I can, would you like to to send a PR? maybe we can copy the function from plug and make a note that its from plug to avoid a dependency on plug.

thank you

**Comment by drapergeek** [comment]
I won't have time to send in a PR anytime soon so I wanted to let you know about the issue.

FWIW, from your lock file, something else is already depending on Plug.

**Comment by allyraza** [comment]
Thank you reporting the bug, I will take a look it at this weekend.

**Comment by allyraza** [comment]
Please update your version to 0.4.0, it has been fixed will close it.
