### ISSUE TITLE
Keep crashing at "Repo.paginate(params)" with the latest Phoenix RC2.

### ISSUE THREAD

**Issue by seymores** [elixirdrops/kerosene#27]
Keep crashing at `Repo.paginate(params)` with the latest Phoenix RC2.

```
8   def index(conn, params) do
9     {users, k} =
10       Admin.list_users |> Repo.paginate(params) <-- crash here
11     render(conn, "index.html", users: users, kerosene: k)
12   end
```
Error raised:
```
** (exit) an exception was raised:
    ** (ArgumentError) argument error
```

**Comment by allyraza** [comment]
@seymores thank you for reporting this, I will try reproduce this today

**Comment by boilercoding** [comment]
@seymores can you show the list_users function of your Admin Repo? It might be an issue with the query of that function.

**Comment by nicolasblanco** [comment]
I've been using this library with 1.3rc2 and lately with the final 1.3 version and it's been working fine...

**Comment by allyraza** [comment]
I could reproduce this, I will close it for now please go ahead reopen it if you can reproduce it with guide to reproduce
