### ISSUE TITLE
scrivener_html?

### ISSUE THREAD

**Issue by mtyeh411** [elixirdrops/kerosene#28]
how is this similar to or different than [scrivener_html](https://github.com/mgwidmann/scrivener_html)?

might be better for the community if there were less packages that were functionally equivalent

**Comment by allyraza** [comment]
I will be honest author of Scrivener posted a blog post before he published a library (Scrivener), I had already implemented pagination in my own app with ideas from the article and extended for my own use case, I pulled it out of the application and converted to a library for my personal use, overtime people have started using it and this what it is today. 

I am also in favor of having few stable libraries that we can develop as a community and use, I don't want elixir/erlang to turn into node/npm

**Comment by mtyeh411** [comment]
```
I don't want elixir/erlang to turn into node/npm
```
@allyraza yeah that's essentially where i was coming from 😆
