### ISSUE TITLE
Group by support

### ISSUE THREAD

**Issue by danturn** [elixirdrops/kerosene#37]
Hi Ally, 

I've raised a PR for group by support against your master... i have just noticed though that pagination doesn't seem to work in master (unless i'm mistaken?). The offset stuff doesn't appear to work and you always get an offset of 1 so page 2 contains almost all the results of page 1
 
I'm going to temporarily fork 0.7.0 and make the group by fix there also but i just wondered if master was in a temporary state and its worth leaving my PR open?

Thanks
Dan

**Comment by allyraza** [comment]
Hey Dan,

Sorry I know I have been delaying your changes for a while I have merged your changes released 0.8.0 please take look I am going to close this for now, please feel free reopen it if you see its not working as expected.

Thank you!
cheers

**Comment by danturn** [comment]
Thanks Ally!

I'll try it out today and let you know if i have any issues

Dan
