### ISSUE TITLE
Ecto 3.0 support

### ISSUE THREAD

**Issue by mtarnovan** [elixirdrops/kerosene#48]
I've started some initial work on this here: https://github.com/mtarnovan/kerosene/tree/ecto-3.0. I think the migration to 3 won't necessitate a lot of changes, mostly things related to pattern matching on the Query struct, which is more structured in Ecto 3. (for example `from` changed from a tuple to a `%Ecto.Query.FromExpr`, etc)

**Comment by nathany** [comment]
I took a look at #47 and updated to Ecto SQL 3.0, but I ran into this test failure. @mtarnovan Did you hit this too?

```
  1) test non schema based queries (KeroseneTest)
     test/kerosene_test.exs:26
     ** (UndefinedFunctionError) function nil.__schema__/1 is undefined
     code: {_items, kerosene} = Repo.paginate(query, %{})
     stacktrace:
       nil.__schema__(:primary_key)
       (kerosene) lib/kerosene.ex:102: Kerosene.get_primary_key/1
       (kerosene) lib/kerosene.ex:83: Kerosene.total_count/1
       (kerosene) lib/kerosene.ex:73: Kerosene.get_total_count/3
       (kerosene) lib/kerosene.ex:29: Kerosene.paginate/3
       test/kerosene_test.exs:32: (test)
```

**Comment by nathany** [comment]
I'm not all that familiar with this part of ecto, but the tests do pass with @theangryangel's:

```
true -> query.from.source |> elem(1)
```

For get_primary_key. That looks far simpler than:

```
true ->
  case query.from do
    %Ecto.Query.FromExpr{source: {_, from}} -> from
    {source, _schema} -> source
  end 
```

However, the other change you made was to `total_count` on line 80, which fixes the test failure mentioned above.

**Comment by mtarnovan** [comment]
@nathany Not sure where you see that test failure. On my branch all tests pass. Have you checked out that branch? https://github.com/mtarnovan/kerosene/tree/ecto-3.0

**Comment by nathany** [comment]
yup. I incorporated one of your fixes into #49. thanks!

**Comment by mtarnovan** [comment]
Glad I could help.

> For get_primary_key. That looks far simpler than:

Indeed. I initially wanted to support both Ecto 2.x and 3.x, but changed my mind and forgot to simplify that code.

**Comment by allyraza** [comment]
Hi everyone, 

great work It has been on my list for some time, I have not had time to work on it.

My employer did not allow me to work on kerosene anymore where it was originally born, I have moved on I am hopping I will have more time to work on it.

thanks once again waiting for the PR ❤️
