### ISSUE TITLE
Pagination breaks after page 100

### ISSUE THREAD

**Issue by mdlkxzmcp** [elixirdrops/kerosene#57]
Everything works as expected, until you try to go to page 101 (or anything bigger than 100). At that point you get teleported to the last page with no way to access anything between 100 and whatever is your last page (in my case that's page 487...)

**Comment by danturn** [comment]
https://github.com/elixirdrops/kerosene/blob/9c7838b1edf310ad0d0522da256943c7590af4d0/lib/kerosene.ex <- i think looking here that the default max_page is 100...

i think you can set this in your config?

**Comment by mdlkxzmcp** [comment]
You are absolutely correct! Didn't expect there to be a value for that... Anyway thank you, closing this issue then :>
