### ISSUE TITLE
Params for Links

### ISSUE THREAD

**Issue by taylorbrooks** [elixirdrops/kerosene#8]
If I hardcode the params in my `paginate` func like so:

````elixir
<%= paginate(@conn, @kerosene, params: %{bing: "bong"} %>
````

I see the return of `build_options` as

````elixir
[
  window: 3, next_label: "Next", 
  previous_label: "Previous", 
  first: true, 
  first_label: "First", 
  last: true, 
  last_label: "Last", 
  params: %{bing: "bong"},
  theme: :bootstrap, 
  path: "/emails?bing=bong"
]
````

So it looks like the `params` and `path` are set appropriately, but the pagination links don't include the query params.

**Comment by taylorbrooks** [comment]
I think https://github.com/elixirdrops/kerosene/blob/master/lib/kerosene/paginator.ex#L14

should read:

````elixir
params = opts[:params] || []
````

**Comment by allyraza** [comment]
I guess you are right it should default to paginator if no params are passed in

**Comment by allyraza** [comment]
@taylorbrooks please bump your kerosene version to 0.3.0 and that should fix it. Thanks

**Comment by taylorbrooks** [comment]
@allyraza Thanks!
