### ISSUE TITLE
Pagination fails for models with custom primary key

### ISSUE THREAD

**Issue by mtarnovan** [elixirdrops/kerosene#9]
I'm seeing errors like this:
```
iex(7)> Company.search("cub") |> Repo.paginate
** (Postgrex.Error) ERROR (undefined_column): column c0.id does not exist
```

The `company` model defines a custom primary key. As far as I can tell, Kerosene assumes the primary key is always "id" (from [here](https://github.com/elixirdrops/kerosene/blob/master/lib/kerosene.ex#L50)) so pagination will fail on models with custom primary key.

**Comment by allyraza** [comment]
@mtarnovan kerosene expects the schema module to have a primary key of id

**Comment by mtarnovan** [comment]
@allyraza You can use something like this in `get_total_count` to extract the primary key from the schema:

```elixir
primary_key =
  query.from |>
  elem(1) |>
  apply(:__schema__, [:primary_key])
  |> hd
```

**Comment by allyraza** [comment]
that would work but I think we should make more explicit by taking in a primary key, maybe we can default to what described

**Comment by mtarnovan** [comment]
It seems a bit superfluous to me to repeat the primary key if it's already defined in the schema, but maybe I didn't understand you suggestion.

**Comment by allyraza** [comment]
Added support for primary keys from structs and queries.

**Comment by mtarnovan** [comment]
👍 @allyraza thanks!
